### ISSUE TITLE
Feature request: add jpg support for v2

### ISSUE THREAD

**Issue by ntfshard** [kornelski/dssim#46]
I saw issue #41 and as far as I understand it's related to v1 implementation
May be it can be easier now to add this feature

**Comment by kornelski** [comment]
It is. It's planned.

**Comment by shaharyar-shamshi** [comment]
@kornelski is it implemented ?

**Comment by kornelski** [comment]
No

**Comment by jeremychone** [comment]
After playing around, I found that  the following that work. Kind of a big perf (2x) penalty since it has to convert to png in memory. 

```rust
use image::{GenericImageView, PNG};
use imgref::{Img, ImgVec};
use lodepng::ColorType;

// .....


fn _load_image(path: &str) -> Result<ImgVec<RGBAPLU>, Error> {
	// load the image with "image" crate
	let image = image::open(path)?;
	let (width, height) = (image.width() as usize, image.height() as usize);

	// write as PNG buffer via "image" crate
	let mut vb: Vec<u8> = Vec::new();
	let _ = image.write_to(&mut vb, PNG);

	// decode the png with lodepng
	let l_img = lodepng::decode_memory(&vb, ColorType::RGBA, 8)?;
	if let lodepng::Image::RGBA(l_img) = l_img {
		return Ok(Img::new(l_img.buffer.to_rgbaplu(), width, height));
	} else {
		return Err(err_msg("can't load image"));
	}
}
```

There might be a more efficient way but `RGBAPLU` seems to be a  lodepng thing  only.

**Comment by mernen** [comment]
Here's a function that will convert an image loaded with `image::open()` without intermediary files:

```rust
use dssim::RGBLU;
use image::{DynamicImage, GenericImageView};
use imgref::ImgVec;
use rgb::RGB;

fn to_imgvec(input: DynamicImage) -> ImgVec<RGBLU> {
    fn float(b: u8) -> f32 {
        b as f32 / 255.0
    }

    let pixels = input
        .as_rgb8()
        .unwrap()
        .pixels()
        .map(|p| {
            let [r, g, b] = p.data;
            RGB::new(float(r), float(g), float(b))
        })
        .collect();
    ImgVec::new(pixels, input.width() as usize, input.height() as usize)
}
```

There are probably more efficient ways around, I'm not familiar with any of the crates involved. Note you'll need to include the crates `image`, `imgref`, and `rgb`.

**Comment by mernen** [comment]
Ah, I see. I was intentionally ignoring the alpha, as I didn't need it, but I wasn't aware of the brightness difference.

Here's an improved version, that will attempt to preserve the alpha channel and properly call `to_rgbaplu()`, at the slight cost of creating two vecs:

```rust
use dssim::{Dssim, RGBAPLU, ToRGBAPLU};
use image::{DynamicImage, GenericImageView};
use imgref::ImgVec;
use rgb::RGBA;

fn to_imgvec(input: DynamicImage) -> ImgVec<RGBAPLU> {
    let pixels: Vec<_> = input
        .as_rgba8()
        .map(|img| {
            img.pixels()
                .map(|p| {
                    let [r, g, b, a] = p.data;
                    RGBA::new(r, g, b, a)
                })
                .collect()
        })
        .or_else(|| {
            input.as_rgb8().map(|img| {
                img.pixels()
                    .map(|p| {
                        let [r, g, b] = p.data;
                        RGBA::new(r, g, b, 255)
                    })
                    .collect()
            })
        })
        .expect("Failed to convert image pixels");
    ImgVec::new(
        pixels.to_rgbaplu(),
        input.width() as usize,
        input.height() as usize,
    )
}
```

**Comment by jeremychone** [comment]
@mernen Thank you for your latest update, works great, and allows to abstract png/jpeg nicely and remove lodepng dependency. 

On a  very minor syntactical note, somehow I cannot get your elegant `Rgba { data: [r, g, b, a] })` mapping to work. I think it is partially due to the image API change (Rgba does not seem to have .data anymore in Image 0.22.x, https://docs.rs/image/0.22.1/image/#structs), but also perhaps something I am missing in Rust. I got the variant working below, but would love to "destructuring" the rgba into variables, rather than having one line for each. 

```rust
fn to_imgvec(input: impl GenericImageView<Pixel = Rgba<u8>>) -> ImgVec<RGBAPLU> {
	let pixels = input
		.pixels()
		.map(|(_x, _y, rgba)| {
			let r = rgba[0];
			let g = rgba[1];
			let b = rgba[2];
			let a = rgba[3];
			RGBA::new(r, g, b, a)
		})
		.collect::<Vec<_>>()
		.to_rgbaplu();
	ImgVec::new(pixels, input.width() as usize, input.height() as usize)
}
```

**Comment by mernen** [comment]
@jeremychone Clicking the "Show declaration" option (that's weird, pretty sure older versions of rustdoc would expand by default), you'll see they've simplified the structure to:

```rust
pub struct Rgba<T: Primitive>(pub [T; 4]);
```

i.e. it's a tuple-like struct now, with a single public unnamed field. That means you can destructure it like `Rgba([r, g, b, a])`.

**Comment by jeremychone** [comment]
@mernen Thank you, this is what I was missing, works like a charm!
`.map(|(_x, _y, Rgba([r, g, b, a]))| RGBA::new(r, g, b, a))`

I went to the source, tried many combinations, but I was (and still) getting confused with this tuple/array/index destructuring. I thought it was an array structure, the macro through me off. I will eventually get it. Thanks!!

**Comment by ThomasLohner** [comment]
Any news on this? I'm really interested in comparing jpg images.

**Comment by kornelski** [comment]
I've released a crate for loading PNG and JPEG, with color profiles: 

https://lib.rs/crates/load_image

Try hooking it up to this crate.

**Comment by ygoe** [comment]
The status of this is unclear. This issue reads like JPEG files are supported in version 2.x. Now version 2.9.7 is available and the readme text still says it only supports PNG. Which is correct?

I'm thinking of putting [this collection of tools](https://github.com/technopagan/cjpeg-dssim) together into a single application. It uses a shell script and imagick to happily convert images between formats and iteratively determine a good JPEG quality value. But it seems rather inefficient to encode to JPEG to test, then convert to PNG for quality estimation, and if good, encode to JPEG again as output. This could me improved a lot by doing it properly in a normal application and avoiding the PNG step completely if all we need is a decoded image. Since this application would require a JPEG en/decoder anyway, it might also be used here if needed. If it could support PNG, JPEG and WebP all in one, that would be great.

Unfortunately I'm not very familiar with C and don't understand anything of Rust so I can't do this.

**Comment by kornelski** [comment]
Done
